### ISSUE TITLE
Potentially reject invalid command-line arguments

### ISSUE THREAD

**Issue by ghost** [medic/horticulturalist#17]
It might be worth exiting with a nonzero status if any invalid command-line options are passed. As a limited-scope option, we could just reject the older pre-0.11 options like `--only-bootstrap` with a "this has been removed" message rather than starting the daemon.

No big deal or blocker, but I wanted to make a note of it.

**Comment by SCdF** [comment]
This is a good and easy idea (I *think* minimist has a simple way of detecting "invalid" command line parameters).

Can you raise this against medic-webapp and low priority for 3.0, and close it here? Otherwise people probably won't see it
