### ISSUE TITLE
Horti should by default install release version and not master

### ISSUE THREAD

**Issue by henokgetachew** [medic/horticulturalist#32]
Right now, horti defaults to installing the master version if unspecified.  What should be the default behavior is installing from the release branch not from master.

**Comment by SCdF** [comment]
Why do you say that should be the default behaviour? 

If you are looking to use horticulturalist to install the latest release version you can currently use `--install=@release` to achieve that, is this helps.

**Comment by SCdF** [comment]
PR here: https://github.com/medic/horticulturalist/pull/37

**Comment by newtewt** [comment]
@SCdF  gave this a look and it's installing the latest release as expected. Feel free to close.
