### ISSUE TITLE
The .horticulturalist.lock file prevents horti from restarting when the medic-os docker container restarts

### ISSUE THREAD

**Issue by Hareet** [medic/horticulturalist#44]
Horti lock file currently saves to `/srv`, persistent storage, which results in horti finding the file present on container reboot.

This file should be placed in the `/tmp` directory which will be refreshed every time the container starts or disabled for production docker use.

**Comment by kennsippell** [comment]
Published as `horticulturalist@0.12.8`

**Comment by garethbowen** [comment]
Reopening so we can AT this change.

**Comment by newtewt** [comment]
I built a local container with these local changes. The lockfile is not there and I'm able to upgrade/downgrade between the different versions. Rebooting also doesn't have anything in the logs since the file isn't there!
