### ISSUE TITLE
Horti doesn't wam all views when deploying 3.9.x+

### ISSUE THREAD

**Issue by dianabarsan** [medic/horticulturalist#57]
In version `3.9.0` of `cht-core`, we changed the name of the attachment that contains all medic-db ddocs (along with adding attachments for ddocs that should be saved in auxiliary databases).
Horticulturalist still expects all ddocs to be compiled in an attachment called `compiled.json`.

Update Horticulturalist so it looks for the new attachment as well.

**Comment by dianabarsan** [comment]
Using the current version of horti, the action of upgrading to 3.9.x will **not warm** any views except those from `_design/medic`. 
This means that, after the upgrade is complete and API boots for the first time, it will be stalled (and on every restart) until all necessary views are warmed (mainly the one from `_design/medic-client`).

**Comment by dianabarsan** [comment]
This is ready for AT on `57-stage-from-medic-json`.

**Comment by newtewt** [comment]
@dianabarsan , I have tested this now in my local container and it seems to work fine. 

I started with 3.7 in a fresh up of medic-os. Disabled the horti service, cloned horti and the branch, started via cli. 
Loaded seed data.
Went to 3.8 and then 3.9.
Went back to 3.7 and then to 3.9. Seeing the console and ui details about warming views. 

I did receive this error, which kills the horti cli. Not sure if this is related or not. 


```
Unexpected error while warming: (Document update conflict.), continuing                                                             ********FATAL********                                                                                                               
{ error: 'conflict',                                                                                                                  
reason: 'Document update conflict.',                                                                                                
status: 409,                                                                                                                       
 name: 'conflict',                                                                                                                   
message: 'Document update conflict.',                                                                                               
docId: 'horti-upgrade' }              

```

**Comment by dianabarsan** [comment]
@newtewt thanks for looking into this so quickly. 
The error you're seeing is unrelated to this fix, please feel free to raise an issue to fix it.

**Comment by dianabarsan** [comment]
Merged into `master`.
